### PR TITLE
feat(Testing Now): Now

### PR DESCRIPTION
**Pull request by danial24**

### CODE REVIEW

**Comment by artalat** [comment]
@danial24 seems deployment was ok, why is it showing failed?

**Comment by danial24** [comment]
@artalat 
what happens is zeit expects a public folder after running yarn run build command
But our web build is not being generated by yarn run build command as that command is for creating the dist for the plugin

So we need to do two things here
First create a web build and the folder structure it expects to have a folder named "public" in the root.

The one that got passed I generated the public folder by adding the following command.

"build:web":"bluebase web:build --static && mkdir public && cp -r ./build/web/client/* ./public",

**Comment by danial24** [comment]
So the problem is bluebase is not know to now configs.

So it is throwing error

What we can do is have a command run before pushing so that it has the latest build folder as public
and now will deploy it 
Or we have to make now know of bluebase cli

**Comment by artalat** [comment]
moving the folder does not seem like a good design, can we change working directory and `cd` into the build folder?

**Comment by artalat** [comment]
is it possible to provide path to custom path to public directory?

**Comment by artalat** [comment]
Now supports a [now.json](https://zeit.co/docs/v2/advanced/configuration/) file.

Also, their CLI support custom path:

Screenshot 2019-08-30 at 4 25 54 PM

**Comment by danial24** [comment]
Yes will move into the directory but the build folder is in gitignore as to create a fresh one every time. So there is no build folder in which I can cd into
As I do not have bluebase cli there which will be needed to build the web app.
Currently working on that
And yes agreed will not generate a public directory, will use a path.

**Comment by danial24** [comment]
@artalat 
Added the following script in package.json in the build heirarchy
The deployment is working on NOW

**Comment by danial24** [comment]
@artalat 
I have tested the deployment. Please review and merge the PR

**Comment by artalat** [comment]
Why do we have to commit the build though? Doesn't seem like a good idea

**Comment by artalat** [comment]
> Yes will move into the directory but the build folder is in gitignore as to create a fresh one every time. So there is no build folder in which I can cd into
> As I do not have bluebase cli there which will be needed to build the web app.
> Currently working on that
> And yes agreed will not generate a public directory, will use a path.

This approach seemed much better

**Comment by danial24** [comment]
It is same like we make a build for making dist.
We will still discuss a better scenario for this.
Will investigate further for some other approach and will discuss it with you.

**Comment by danial24** [comment]
The main thing was to have bluebase cli in the now environment.
Because the build folder is in gitignore.
So we have to create the build to have it uploaded. That is why added the cli install commands which just generate the build folder.

**Comment by danial24** [comment]
> > Yes will move into the directory but the build folder is in gitignore as to create a fresh one every time. So there is no build folder in which I can cd into
> > As I do not have bluebase cli there which will be needed to build the web app.
> > Currently working on that
> > And yes agreed will not generate a public directory, will use a path.
> 
> This approach seemed much better

This is the same I am doing 
As the public folder being created is discarded.
The cli is available as well there now.

**Comment by artalat** [comment]
To have the BlueBase CLI available, an alternate approach can be to [Deploy via Travis](https://docs.travis-ci.com/user/deployment). This means ditching now app though, but you get to have the flexibility to anything you would want to as you would on shell.

**Comment by danial24** [comment]
I understand.Ok will see the other approach as well and will let you know.

**Comment by danial24** [comment]
@artalat 
Will be needing the auth token of Now. I guess the token tab is not being shown to me due to some permission issues. 
Please go to https://zeit.co/account/tokens
And provide me one, I will be needing that to run "now command on travis"

**Comment by artalat** [comment]
Hello world

**Comment by abubakarmani1** [comment]
Hello world

**Comment by abubakarmani1** [comment]
Test Comment

**Comment by abubakarmani1** [comment]
https://plugin-launcher-o8kxzmrl7.now.sh

**Comment by abubakarmani1** [comment]
Build Path: https://plugin-launcher-o8kxzmrl7.now.sh

**Comment by artalat** [comment]
Build Path:

**Comment by artalat** [comment]
@danial24 you not just do `node ./scripts/deploy-to-now.js`. And write all your logic in js, will be much more flexible and you use SDKs? You will not have to push code to test every time as well.

We may even be able to move this script to `bluebase web:publish` command or something?

**Comment by artalat** [comment]
Can we use custom templates? I was thinking something like this:

---

This pull request is automatically deployed on [Now (Web)](https://plugin-launcher-fq5b4h0qk.now.sh/) and [Expo (Native)](https://expo.io/@bluebase/launcher).

To access deployments, scan the QR Code, click Details below or on the icon next to each push.

| Web | Native |
|---|---|
| Web | Web |

**Comment by artalat** [comment]
Build Path: https://client-crm23ge3b.now.sh

**Comment by artalat** [comment]
Build Path: https://client-ff88q0yur.now.sh

**Comment by artalat** [comment]
Build Path: https://client-9h3rz4yss.now.sh

**Comment by artalat** [comment]
We now have a custom pipeline. So there is no need of this PR.

**Pull request closed without merging**
